"""init mysql

Revision ID: 3db80a65668b
Revises: 
Create Date: 2025-12-22 23:00:53.626005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3db80a65668b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agent_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True, comment='配置名称'),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('system_prompt', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('emotion_recognition_rules', mysql.JSON(), nullable=True, comment='情绪识别规则与干预策略'),
    sa.Column('style_config', mysql.JSON(), nullable=True, comment='语言风格与禁词'),
    sa.Column('scoring_rules', mysql.JSON(), nullable=True, comment='SCL90评分映射规则'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否为当前生效版本'),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['question_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('last_assessment_at', sa.DateTime(), nullable=True, comment='最近一次完成测评的时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('ai_agent_config_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_config_id', sa.Integer(), nullable=True),
    sa.Column('version_tag', sa.String(length=50), nullable=True, comment='版本号如 202512初始版'),
    sa.Column('config_snapshot', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['original_config_id'], ['ai_agent_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_agent_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False, comment='问题内容'),
    sa.Column('dimension', sa.String(length=50), nullable=True, comment='关联维度'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='优先级 1-5'),
    sa.Column('scoring_match_rule', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['ai_agent_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='ongoing, completed'),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('chat_history', mysql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('export_range', mysql.JSON(), nullable=True, comment='筛选条件快照'),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_url', sa.String(length=512), nullable=True),
    sa.Column('file_size', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='processing, success, failed'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True, comment='操作模块'),
    sa.Column('action', sa.String(length=50), nullable=True, comment='具体动作'),
    sa.Column('target_id', sa.Integer(), nullable=True, comment='操作对象ID'),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True, comment='success/failure'),
    sa.Column('details', sa.Text(), nullable=True, comment='备注或失败原因'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False, comment='题干'),
    sa.Column('type', sa.String(length=20), nullable=True, comment='题型'),
    sa.Column('difficulty', sa.String(length=20), nullable=True, comment='难度'),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['question_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True, comment='功能/体验/结果疑问'),
    sa.Column('images', mysql.JSON(), nullable=True, comment='上传的图片URL列表'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='pending, processing, replied, closed'),
    sa.Column('admin_reply', sa.Text(), nullable=True, comment='管理员回复内容'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('summary_short', sa.String(length=255), nullable=True, comment='综合心理状态标签'),
    sa.Column('detail_content_md', mysql.MEDIUMTEXT(), nullable=True, comment='Markdown详情'),
    sa.Column('radar_data', mysql.JSON(), nullable=True, comment='雷达图数据'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='风险等级'),
    sa.Column('high_risk_dimensions', mysql.JSON(), nullable=True, comment='核心高风险维度'),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('assessment_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_reports_risk_level'), ['risk_level'], unique=False)

    op.create_table('question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True, comment='选项名：没有/很轻/中等...'),
    sa.Column('score', sa.Integer(), nullable=True, comment='分值：1-5'),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_options')
    with op.batch_alter_table('assessment_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_reports_risk_level'))

    op.drop_table('assessment_reports')
    op.drop_table('user_feedbacks')
    op.drop_table('questions')
    op.drop_table('operation_logs')
    op.drop_table('export_records')
    op.drop_table('assessment_sessions')
    op.drop_table('ai_agent_questions')
    op.drop_table('ai_agent_config_versions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))

    op.drop_table('users')
    op.drop_table('question_categories')
    op.drop_table('ai_agent_configs')
    # ### end Alembic commands ###
